services:
  api:
      build: .
      container_name: DjangoAPI
      command: >
        bash -c "python manage.py collectstatic --no-input &&
        python manage.py makemigrations --no-input&&
        python manage.py migrate --no-input &&
        gunicorn --bind 0.0.0.0:8000 config.wsgi:application --timeout 200 --workers=5"
      ports:
        - 8000:8000
      # - 587:587
      restart: always
      volumes:
        - .:/code
        - static_volume:/code/static/
      environment:
        - SECRET_KEY=${SECRET_KEY}
        - DEBUG=${DEBUG}
        - PROD=${PROD}
        - DEV=${DEV}
        - TEST=${TEST}
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - REDIS_URL=${REDIS_URL}
        - CELERY_BROKER_URL=${CELERY_BROKER_URL}
        - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      networks:
        api_network:

# Celery Service
  celery:
    build: .
    container_name: Celery
    command: celery -A config worker --loglevel=info
    volumes:
        - .:/code
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - PROD=${PROD}
      - DEV=${DEV}
      - TEST=${TEST}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - REDIS_URL=${REDIS_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
        - api
        - redis
    networks:
      api_network:

  #Redis Service
  redis:
    container_name: Redis
    image: "redis:7.2-alpine"
    networks:
      api_network:

  
volumes:
  # will be used to store our ssl certificate and make it persistent as wel   
  postgres_data:
  static_volume:
    
networks:
  api_network:


  