# Generated by Django 4.1 on 2024-07-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_alter_bike_cost_per_minute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='cost_per_minute',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
        ),
    ]
