# Generated by Django 5.0.7 on 2024-07-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='Users',
        ),
    ]
